#!/usr/bin/env ruby
require 'webrick'

mime_types = WEBrick::HTTPUtils::DefaultMimeTypes
mime_types.store('js', 'application/javascript')
mime_types.store('json', 'application/json')

server = WEBrick::HTTPServer.new(
    :Port => ARGV[0].to_i || 8000, 
    :DocumentRoot => File.expand_path("#{ARGV[1].to_s}" || '.'), 
    :MimeTypes => mime_types).start

