#!/usr/bin/env ruby
require 'webrick'

port = ARGV[0].to_i || 8000
root = File.expand_path "#{ARGV[1].to_s}" || '.'
server = WEBrick::HTTPServer.new :Port => port, :DocumentRoot => root
server.start

